-- ============================================================================
-- SEED — PRODUCT CATALOG from the live showroom
-- ----------------------------------------------------------------------------
-- GENERATED FILE — do not edit by hand.
--   pnpm exec node scripts/generate-catalog-seed.mjs
--
-- Source of truth: components/showroom-section.tsx (names, descriptions,
-- materials, specs, CDN images) and lib/showroom.ts (category names).
--
-- Run AFTER supabase/migrations/0002_products_catalog.sql.
--
--   * 'on conflict (name) do nothing' => re-running is safe and never
--     overwrites a product an admin has edited, renamed or deactivated.
--   * price_per_unit is left NULL on purpose: the showroom publishes no prices
--     because quotes are negotiated. Set prices in /admin/products.
--   * moq_units is NULL for the 38 products whose showroom entry publishes no
--     "Minimum order quantity" spec — the site never stated one, so the seed
--     does not invent one. Fill them in at /admin/products.
--   * images[].fileId is NULL: these files were uploaded to ImageKit outside
--     this app, so the admin UI will never delete them from the CDN.
--   * width_mm stores the nominal lower bound of the published range.
-- ============================================================================

INSERT INTO products (
  name, category, category_id, type, description, material, width_mm,
  available_colors, available_finishes, moq_units, currency, is_active, specs, images
) VALUES
  ('Fringe Lace', 'Lace', (SELECT id FROM product_categories WHERE lower(name) = lower('Lace')), 'LACE', 'Soft, expressive fringe for trims and statement edges.', 'Cotton blend', 10, '{}'::text[], ARRAY['Natural']::text[], 500, 'PKR', true, '[["Product type","Fringe lace"],["Material composition","Cotton blend"],["Available widths","10mm�50mm"],["Minimum order quantity","500 meters"],["Color options","Custom color matching"],["Finish","Natural / brushed"],["Lead time","2�3 weeks"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/all_Cotton_Fringe.webp","fileId":"6aae1541ead997d09ae5c48b","name":"all_Cotton_Fringe.webp","width":null,"height":null}]'::jsonb),
  ('Golden Tassel', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'TASSEL', 'A polished accent with a warm metallic finish for elevated details.', 'Polyester', 30, ARRAY['Gold tones']::text[], ARRAY['Metallic']::text[], 250, 'PKR', true, '[["Product type","Decorative tassel"],["Material composition","Polyester"],["Available widths","30mm�80mm"],["Minimum order quantity","250 pieces"],["Finish","Metallic"],["Lead time","3�4 weeks"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Golden_Tassel.webp","fileId":"6aae1546ead997d09ae5d7ff","name":"Golden_Tassel.webp","width":null,"height":null}]'::jsonb),
  ('Metal Cord', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'CORD', 'Structured cord with a refined surface texture.', 'Metallic yarn', 2, '{}'::text[], ARRAY['Polished']::text[], 500, 'PKR', true, '[["Product type","Metal cord"],["Material composition","Metallic yarn"],["Available widths","2mm�8mm"],["Minimum order quantity","500 meters"],["Finish","Polished"],["Lead time","3 weeks"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Metal%20Cord.webp","fileId":null,"name":"Metal Cord.webp","width":null,"height":null}]'::jsonb),
  ('Pom Pom Trim', 'Pom Poms', (SELECT id FROM product_categories WHERE lower(name) = lower('Pom Poms')), 'POM POM', 'Playful volume for apparel and home details.', 'Polyester', 10, '{}'::text[], ARRAY['Soft']::text[], 500, 'PKR', true, '[["Product type","Pom pom trim"],["Material composition","Polyester"],["Available widths","10mm�25mm"],["Minimum order quantity","500 meters"],["Finish","Soft"],["Lead time","2�3 weeks"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Pom_Pom_Trim.webp","fileId":"6aae154eead997d09ae5ffe1","name":"Pom_Pom_Trim.webp","width":null,"height":null}]'::jsonb),
  ('Cotton Fringe', 'Lace', (SELECT id FROM product_categories WHERE lower(name) = lower('Lace')), 'FRINGE', 'Natural cotton texture with an easy, soft hand.', '100% cotton', 25, '{}'::text[], ARRAY['Natural']::text[], 500, 'PKR', true, '[["Product type","Cotton fringe"],["Material composition","100% cotton"],["Available widths","25mm�100mm"],["Minimum order quantity","500 meters"],["Finish","Natural"],["Lead time","3 weeks"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Cotton_Fringe.webp","fileId":"6aae1551ead997d09ae60efb","name":"Cotton_Fringe.webp","width":null,"height":null}]'::jsonb),
  ('Woven Belt', 'Belts', (SELECT id FROM product_categories WHERE lower(name) = lower('Belts')), 'UTILITY', 'Hard-wearing woven utility trim made for scale.', 'Polyester', 25, '{}'::text[], ARRAY['Durable']::text[], 500, 'PKR', true, '[["Product type","Woven utility belt"],["Material composition","Polyester"],["Available widths","25mm�40mm"],["Minimum order quantity","500 meters"],["Finish","Durable woven"],["Lead time","3 weeks"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Woven%20Belt.png","fileId":null,"name":"Woven Belt.png","width":null,"height":null}]'::jsonb),
  ('Needle Loom Elastic', 'Elastics', (SELECT id FROM product_categories WHERE lower(name) = lower('Elastics')), 'ELASTIC', 'Strong, durable elastic with a soft and smooth finish.', 'Nylon / Polyester', NULL, ARRAY['White', 'Black', 'Natural', 'Beige', 'Grey', 'Navy Blue', 'Brown', 'Multi Color']::text[], ARRAY['Soft / Smooth']::text[], NULL, 'PKR', true, '[["Product type","Needle loom elastic"],["Material composition","Nylon / Polyester"],["Available widths","Various"],["Color options","Multiple colors"],["Finish","Soft / smooth"],["Applications","Collars, cuffs, waistbands"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Needle_Loom_Elastic.webp","fileId":"6aae1556ead997d09ae61b93","name":"Needle_Loom_Elastic.webp","width":null,"height":null}]'::jsonb),
  ('Crochet Elastic', 'Elastics', (SELECT id FROM product_categories WHERE lower(name) = lower('Elastics')), 'ELASTIC', 'Stretchy, durable crochet elastic designed for comfortable textile applications.', 'Latex / Polyester', NULL, ARRAY['White', 'Black', 'Beige', 'Grey', 'Navy Blue', 'Multi Color']::text[], ARRAY['Soft / Flexible']::text[], NULL, 'PKR', true, '[["Product type","Crochet elastic"],["Material composition","Latex / Polyester"],["Available widths","Various"],["Color options","Multiple colors"],["Finish","Soft / flexible"],["Applications","Waistbands, undergarments, crafts"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Crochet%20Elastic.png","fileId":null,"name":"Crochet Elastic.png","width":null,"height":null}]'::jsonb),
  ('Jacquard Elastic & Tape', 'Elastics', (SELECT id FROM product_categories WHERE lower(name) = lower('Elastics')), 'ELASTIC', 'Strong jacquard elastic and tape with custom branding and woven designs.', 'Nylon / Polyester', NULL, '{}'::text[], ARRAY['Woven / Jacquard']::text[], NULL, 'PKR', true, '[["Product type","Jacquard elastic & tape"],["Material composition","Nylon / Polyester"],["Available widths","Custom"],["Color options","Custom color matching"],["Design options","Logo, text, branded, custom"],["Finish","Woven / jacquard"],["Applications","Garments, waistbands, sportswear"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Jacquard_Elastic___Tape.webp","fileId":"6aae155bead997d09ae63363","name":"Jacquard_Elastic___Tape.webp","width":null,"height":null}]'::jsonb),
  ('Elastics', 'Elastics', (SELECT id FROM product_categories WHERE lower(name) = lower('Elastics')), 'ELASTIC', 'General-purpose textile elastics available in multiple materials and colors.', 'Nylon / Polyester / Polypropylene', NULL, ARRAY['Multiple colors']::text[], ARRAY['Flexible']::text[], NULL, 'PKR', true, '[["Product type","General elastic"],["Material composition","Nylon / Polyester / Polypropylene"],["Available widths","Various"],["Color options","Multiple colors"],["Finish","Flexible"],["Applications","Garment industry"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Loom%20Elastic_XnZ43cMo2.webp","fileId":null,"name":"Loom Elastic_XnZ43cMo2.webp","width":null,"height":null}]'::jsonb),
  ('Draw Cord', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'CORD', 'Strong and flexible draw cord available in solid, striped and patterned designs.', 'Nylon / Polyester / Polypropylene / Cotton', NULL, ARRAY['Custom', 'Multiple colors']::text[], ARRAY['Various finishes']::text[], NULL, 'PKR', true, '[["Product type","Draw cord"],["Material composition","Nylon / Polyester / Polypropylene / Cotton"],["Available widths","Various"],["Color options","Solid, striped, reflective, two-tone, multi color"],["Design options","Flat, round, patterned, custom"],["Finish","Various finishes"],["Applications","Hoodies, bags, garments, sportswear"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Draw%20Cord.avif","fileId":null,"name":"Draw Cord.avif","width":null,"height":null}]'::jsonb),
  ('Flat Draw Cord', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'CORD', 'Strong, smooth flat draw cord for garment and sportswear applications.', 'Polyester / Nylon', NULL, ARRAY['Blue', 'White', 'Black', 'White', 'Green', 'White', 'Red', 'White', 'Purple', 'White', 'Multi Color']::text[], ARRAY['Soft / Smooth']::text[], NULL, 'PKR', true, '[["Product type","Flat draw cord"],["Material composition","Polyester / Nylon"],["Available widths","Various"],["Color options","Multiple combinations"],["Finish","Soft / smooth"],["Applications","Hoods, waistbands, sportswear"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Flat_Draw_Cord.webp","fileId":"6aae1562ead997d09ae642d3","name":"Flat_Draw_Cord.webp","width":null,"height":null}]'::jsonb),
  ('Drawstring Cord', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'CORD', 'Durable, flexible drawstring cord available in a range of finishes.', 'Polyester / Nylon', NULL, ARRAY['Custom', 'Multiple colors']::text[], ARRAY['Various finishes']::text[], NULL, 'PKR', true, '[["Product type","Drawstring cord"],["Material composition","Polyester / Nylon"],["Available widths","Various"],["Color options","Multiple colors"],["Finish","Various finishes"],["Applications","Hoodies, bags, garments"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Drawstring_Cord.webp","fileId":"6aae1564ead997d09ae648df","name":"Drawstring_Cord.webp","width":null,"height":null}]'::jsonb),
  ('Cord with Tassel', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'TASSEL', 'Decorative cord finished with an elegant tassel end.', 'Polyester / Synthetic fiber', NULL, ARRAY['Gold', 'Gold', 'Metallic']::text[], ARRAY['Metallic']::text[], NULL, 'PKR', true, '[["Product type","Cord with tassel"],["Material composition","Polyester / synthetic fiber"],["Available widths","Various"],["Color options","Gold, Gold/Metallic"],["Finish","Metallic"],["Applications","Garments, bags, accessories, crafts"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Cord_with_Tassel.webp","fileId":"6aae156bead997d09ae66596","name":"Cord_with_Tassel.webp","width":null,"height":null}]'::jsonb),
  ('Draw Cord Tassel', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'TASSEL', 'Colorful decorative tassel finish for drawstrings and accessories.', 'Synthetic fiber', NULL, ARRAY['Multi Color']::text[], ARRAY['Tassel']::text[], NULL, 'PKR', true, '[["Product type","Draw cord tassel"],["Material composition","Synthetic fiber"],["Available widths","Various"],["Color options","Multi-color tassels"],["Finish","Tassel"],["Applications","Drawstrings, bags, hoodies, accessories"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Draw_Cord_with_Tassel.webp","fileId":"6aae1578ead997d09ae67ce3","name":"Draw_Cord_with_Tassel.webp","width":null,"height":null}]'::jsonb),
  ('Multi Color Tassel', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'TASSEL', 'Soft, colorful fringed tassels available in different lengths.', 'Synthetic fiber', NULL, ARRAY['Multi Color']::text[], ARRAY['Fringed']::text[], NULL, 'PKR', true, '[["Product type","Multi color tassel"],["Material composition","Synthetic fiber"],["Available widths","Various"],["Color options","Multi-color"],["Available lengths","Various"],["Finish","Fringed"],["Applications","Garments, bags, crafts, home decor"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Multi_Color_Tassel.webp","fileId":"6aae1584ead997d09ae6c466","name":"Multi_Color_Tassel.webp","width":null,"height":null}]'::jsonb),
  ('Tassels', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'TASSEL', 'Classic decorative tassels for garments, bags, and home d�cor.', 'Polyester / Synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Decorative']::text[], NULL, 'PKR', true, '[["Product type","Tassels"],["Material composition","Polyester / synthetic fiber"],["Available widths","Various"],["Color options","Multiple colors"],["Finish","Decorative"],["Applications","Garments, bags, home decor"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Tassel.webp","fileId":"6aacce4cead997d09a8a1a21","name":"Tassel.webp","width":null,"height":null}]'::jsonb),
  ('Flat Shoelaces', 'Shoelaces', (SELECT id FROM product_categories WHERE lower(name) = lower('Shoelaces')), 'SHOELACE', 'Durable flat shoelaces available in multiple colors and patterns.', 'Polyester / Nylon', NULL, ARRAY['White', 'Black', 'Grey', 'Navy Blue', 'Red', 'Royal Blue', 'Beige', 'Brown', 'Neon Green', 'Purple Metallic', 'White', 'Cream', 'Black', 'White Striped', 'Orange', 'Tan Metallic', 'Cream', 'Beige', 'Yellow', 'Green', 'Patterned', 'Multi Color']::text[], ARRAY['Woven / Soft']::text[], NULL, 'PKR', true, '[["Product type","Flat shoelace"],["Material composition","Polyester / Nylon"],["Available widths","Various"],["Color options","Multiple colors and patterns"],["Finish","Woven / soft"],["Applications","Sneakers, shoes, boots, hoodies"],["Customization","Custom length, colors and patterns"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Flat_Shoelaces.webp","fileId":"6aae1594ead997d09ae6fe4c","name":"Flat_Shoelaces.webp","width":null,"height":null}]'::jsonb),
  ('Waxy Shoelaces', 'Shoelaces', (SELECT id FROM product_categories WHERE lower(name) = lower('Shoelaces')), 'SHOELACE', 'High-strength wax-coated shoelaces designed for durability and a tangle-free finish.', 'Polyester / Nylon', NULL, ARRAY['Black', 'Brown', 'Dark Brown', 'Navy Blue', 'Grey', 'White', 'Beige', 'Multi Color']::text[], ARRAY['Wax Coated']::text[], NULL, 'PKR', true, '[["Product type","Waxy shoelace"],["Material composition","Polyester / Nylon"],["Available widths","Various"],["Color options","Multiple colors"],["Finish","Wax coated"],["Features","High strength, tangle free, water resistant"],["Applications","Shoes and boots"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Waxy_Shoelaces.webp","fileId":"6aae1597ead997d09ae70686","name":"Waxy_Shoelaces.webp","width":null,"height":null}]'::jsonb),
  ('Tricot Knitting Tape', 'Tapes', (SELECT id FROM product_categories WHERE lower(name) = lower('Tapes')), 'TAPE', 'Strong and smooth knitted tape for garment construction and finishing.', 'Polyester / Nylon', NULL, ARRAY['White', 'White', 'Navy', 'White', 'Black', 'Red', 'White', 'Black', 'Red', 'Green', 'Multi', 'Silver Stripe']::text[], ARRAY['Soft / Smooth']::text[], NULL, 'PKR', true, '[["Product type","Tricot knitting tape"],["Material composition","Polyester / Nylon"],["Available widths","Various"],["Color options","Multiple combinations"],["Finish","Soft / smooth"],["Applications","Collars, cuffs, waistbands"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Tricot_Knitting_Tape.webp","fileId":"6aae1599ead997d09ae70be7","name":"Tricot_Knitting_Tape.webp","width":null,"height":null}]'::jsonb),
  ('Twill Tape', 'Tapes', (SELECT id FROM product_categories WHERE lower(name) = lower('Tapes')), 'TAPE', 'Strong and flexible twill tape available in multiple widths and colors.', 'Cotton / Polyester', 10, ARRAY['Multiple colors']::text[], ARRAY['Twill Weave']::text[], NULL, 'PKR', true, '[["Product type","Twill tape"],["Material composition","Cotton / Polyester"],["Available widths","10mm, 15mm, 20mm, 25mm, 30mm, 38mm, 50mm"],["Color options","Multiple colors"],["Finish","Twill weave"],["Applications","Garments, bags, accessories"],["Customization","Custom width, length and colors"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Twill_Tape.webp","fileId":"6aae159cead997d09ae71cda","name":"Twill_Tape.webp","width":null,"height":null}]'::jsonb),
  ('Neck Tapes', 'Tapes', (SELECT id FROM product_categories WHERE lower(name) = lower('Tapes')), 'TAPE', 'Soft woven neck tape designed for comfortable garment finishing.', 'Polyester / Nylon', NULL, ARRAY['Red', 'Green', 'Light Blue', 'Black', 'White', 'Beige', 'Royal Blue', 'Mint', 'Purple', 'Multipack']::text[], ARRAY['Soft / Woven']::text[], NULL, 'PKR', true, '[["Product type","Neck tape"],["Material composition","Polyester / Nylon"],["Available widths","Various"],["Color options","Multiple colors"],["Finish","Soft / woven"],["Applications","T-shirts, polos, hoodies, jackets, sportswear"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Neck%20Tapes.png","fileId":null,"name":"Neck Tapes.png","width":null,"height":null}]'::jsonb),
  ('Mesh Ribbon', 'Ribbons', (SELECT id FROM product_categories WHERE lower(name) = lower('Ribbons')), 'RIBBON', 'Soft, breathable decorative mesh ribbon for textile and craft applications.', 'Polyester', NULL, ARRAY['White']::text[], ARRAY['Soft / Breathable']::text[], NULL, 'PKR', true, '[["Product type","Mesh ribbon"],["Material composition","Polyester"],["Available widths","Various"],["Color options","White"],["Finish","Soft / breathable"],["Applications","Garments, crafts, gift wrapping, accessories"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Mesh_Ribbon.webp","fileId":"6aae15a0ead997d09ae72b8e","name":"Mesh_Ribbon.webp","width":null,"height":null}]'::jsonb),
  ('Ribbons', 'Ribbons', (SELECT id FROM product_categories WHERE lower(name) = lower('Ribbons')), 'RIBBON', 'Decorative ribbons available in multiple colors and widths.', 'Polyester / Synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Decorative']::text[], NULL, 'PKR', true, '[["Product type","Ribbons"],["Material composition","Polyester / synthetic fiber"],["Available widths","Various"],["Color options","Multiple colors"],["Finish","Decorative"],["Applications","Garments, crafts, gift wrapping, accessories"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Ribbons.webp","fileId":"6aacce43ead997d09a88ffb8","name":"Ribbons.webp","width":null,"height":null}]'::jsonb),
  ('Web Tape', 'Tapes', (SELECT id FROM product_categories WHERE lower(name) = lower('Tapes')), 'TAPE', 'Clean woven construction for dependable finishing and repeat production.', 'Polyester / Polypropylene', NULL, ARRAY['Various']::text[], ARRAY['Woven']::text[], NULL, 'PKR', true, '[["Product type","Web tape"],["Material composition","Polyester / Polypropylene"],["Available widths","Various"],["Color options","Various"],["Finish","Woven"],["Applications","Garments, bags, accessories"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Web_Tape.webp","fileId":"6aae15a6ead997d09ae74155","name":"Web_Tape.webp","width":null,"height":null}]'::jsonb),
  ('Jute Tape', 'Tapes', (SELECT id FROM product_categories WHERE lower(name) = lower('Tapes')), 'TAPE', 'Natural, strong and biodegradable jute tape.', 'Jute', NULL, ARRAY['Natural', 'Multiple colors']::text[], ARRAY['Natural']::text[], NULL, 'PKR', true, '[["Product type","Jute tape"],["Material composition","Jute"],["Available widths","Various"],["Color options","Natural and multiple colors"],["Finish","Natural"],["Applications","Crafts, packaging, home decor"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Jute_Tape.webp","fileId":"6aae15a8ead997d09ae74621","name":"Jute_Tape.webp","width":null,"height":null}]'::jsonb),
  ('Label Tape', 'Tapes', (SELECT id FROM product_categories WHERE lower(name) = lower('Tapes')), 'TAPE', 'Printable label tape for branding and garment identification.', 'Polyester', NULL, ARRAY['Multiple colors']::text[], ARRAY['Printable']::text[], NULL, 'PKR', true, '[["Product type","Label tape"],["Material composition","Polyester"],["Available widths","Various"],["Color options","Multiple colors"],["Finish","Printable"],["Applications","Garments, branding, identification"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Label_Tape.webp","fileId":"6aae15acead997d09ae76227","name":"Label_Tape.webp","width":null,"height":null}]'::jsonb),
  ('Waist Belt', 'Belts', (SELECT id FROM product_categories WHERE lower(name) = lower('Belts')), 'UTILITY', 'Recycled material belt for sustainable garment production.', 'Recycled material', NULL, ARRAY['Various']::text[], ARRAY['Utility']::text[], NULL, 'PKR', true, '[["Product type","Waist belt"],["Material composition","Recycled material"],["Available widths","Various"],["Color options","Various"],["Finish","Utility"],["Applications","Garments, sustainable production"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Waste_Belt.webp","fileId":"6aae1625ead997d09ae96a1b","name":"Waste_Belt.webp","width":null,"height":null}]'::jsonb),
  ('Cotton Belts', 'Belts', (SELECT id FROM product_categories WHERE lower(name) = lower('Belts')), 'UTILITY', 'Natural cotton belt available in multiple widths and colors.', '100% Cotton', NULL, ARRAY['Multiple colors']::text[], ARRAY['Natural / Soft']::text[], NULL, 'PKR', true, '[["Product type","Cotton belt"],["Material composition","100% Cotton"],["Available widths","Various"],["Color options","Multiple colors"],["Finish","Natural / soft"],["Applications","Garments, bags, accessories"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Cotton_Belts.webp","fileId":"6aae15b1ead997d09ae77161","name":"Cotton_Belts.webp","width":null,"height":null}]'::jsonb),
  ('All Types Belts', 'Belts', (SELECT id FROM product_categories WHERE lower(name) = lower('Belts')), 'UTILITY', 'Multi-material belts including nylon, polyester, polypropylene, and cotton.', 'Nylon / Polyester / Polypropylene / Cotton', NULL, ARRAY['Multiple colors']::text[], ARRAY['Woven']::text[], NULL, 'PKR', true, '[["Product type","Multi-type belt"],["Material composition","Nylon / Polyester / Polypropylene / Cotton"],["Available widths","Various"],["Color options","Multiple colors"],["Finish","Woven"],["Applications","Garments, bags, accessories"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/all_Cotton_Belts.webp","fileId":"6aae15b4ead997d09ae77cda","name":"all_Cotton_Belts.webp","width":null,"height":null}]'::jsonb),
  ('Pom-pom', 'Pom Poms', (SELECT id FROM product_categories WHERE lower(name) = lower('Pom Poms')), 'POM POM', 'Soft, playful pom-poms available in multiple colors and sizes.', 'Acrylic / synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Plush']::text[], NULL, 'PKR', true, '[["Product type","Pom-pom"],["Material composition","Acrylic / synthetic fiber"],["Available sizes","Various"],["Color options","Multiple colors"],["Finish","Soft / plush"],["Applications","Garments, crafts, home decor"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Pom_Pom.webp","fileId":"6aae15b6ead997d09ae78336","name":"Pom_Pom.webp","width":null,"height":null}]'::jsonb),
  ('Pom Pom Lace', 'Pom Poms', (SELECT id FROM product_categories WHERE lower(name) = lower('Pom Poms')), 'POM POM', 'Decorative pom-pom lace trim for garments and accessories.', 'Acrylic / synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Plush']::text[], NULL, 'PKR', true, '[["Product type","Pom pom lace"],["Material composition","Acrylic / synthetic fiber"],["Available widths","Various"],["Color options","Multiple colors"],["Finish","Soft / plush"],["Applications","Garments, accessories, crafts"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Pom_Pom_lace.webp","fileId":"6aae15b8ead997d09ae78dfb","name":"Pom_Pom_lace.webp","width":null,"height":null}]'::jsonb),
  ('Pom Pom Ball', 'Pom Poms', (SELECT id FROM product_categories WHERE lower(name) = lower('Pom Poms')), 'POM POM', 'Round pom-pom balls available in multiple sizes and colors.', 'Acrylic / synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Plush']::text[], NULL, 'PKR', true, '[["Product type","Pom pom ball"],["Material composition","Acrylic / synthetic fiber"],["Available sizes","Various"],["Color options","Multiple colors"],["Finish","Soft / plush"],["Applications","Garments, crafts, home decor"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Pom_Pom_Ball.webp","fileId":"6aae15baead997d09ae79fe5","name":"Pom_Pom_Ball.webp","width":null,"height":null}]'::jsonb),
  ('Pom Pom Toys', 'Pom Poms', (SELECT id FROM product_categories WHERE lower(name) = lower('Pom Poms')), 'POM POM', 'Soft, playful pom-pom toys for children and crafts.', 'Acrylic / synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Playful']::text[], NULL, 'PKR', true, '[["Product type","Pom pom toy"],["Material composition","Acrylic / synthetic fiber"],["Available sizes","Various"],["Color options","Multiple colors"],["Finish","Soft / playful"],["Applications","Toys, crafts, children products"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Pom_Pom_toys.webp","fileId":"6aae15bdead997d09ae7ad70","name":"Pom_Pom_toys.webp","width":null,"height":null}]'::jsonb),
  ('Pom Pom Flower', 'Pom Poms', (SELECT id FROM product_categories WHERE lower(name) = lower('Pom Poms')), 'POM POM', 'Decorative pom-pom flowers for garments and home d�cor.', 'Acrylic / synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Decorative']::text[], NULL, 'PKR', true, '[["Product type","Pom pom flower"],["Material composition","Acrylic / synthetic fiber"],["Available sizes","Various"],["Color options","Multiple colors"],["Finish","Soft / decorative"],["Applications","Garments, home decor, crafts"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Pom_Pom_Flower.webp","fileId":"6aae15bfead997d09ae7b596","name":"Pom_Pom_Flower.webp","width":null,"height":null}]'::jsonb),
  ('Multi Pom Pom', 'Pom Poms', (SELECT id FROM product_categories WHERE lower(name) = lower('Pom Poms')), 'POM POM', 'Multi-colored pom-poms available in various sizes.', 'Acrylic / synthetic fiber', NULL, ARRAY['Multi Color']::text[], ARRAY['Soft / Plush']::text[], NULL, 'PKR', true, '[["Product type","Multi pom pom"],["Material composition","Acrylic / synthetic fiber"],["Available sizes","Various"],["Color options","Multi-color"],["Finish","Soft / plush"],["Applications","Garments, crafts, home decor"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Multi_Pom_Pom.webp","fileId":"6aae15c1ead997d09ae7ba28","name":"Multi_Pom_Pom.webp","width":null,"height":null}]'::jsonb),
  ('Party Hat / Birthday Cap', 'Accessories', (SELECT id FROM product_categories WHERE lower(name) = lower('Accessories')), 'PARTY', 'Decorative party hats and birthday caps available in multiple colors.', 'Paper / Cardboard / Synthetic', NULL, ARRAY['Multiple colors']::text[], ARRAY['Decorative']::text[], NULL, 'PKR', true, '[["Product type","Party hat / birthday cap"],["Material composition","Paper / cardboard / synthetic"],["Available sizes","Various"],["Color options","Multiple colors"],["Finish","Decorative"],["Applications","Birthday parties, celebrations, events"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Party_Hat.webp","fileId":"6aae15c3ead997d09ae7c0a7","name":"Party_Hat.webp","width":null,"height":null}]'::jsonb),
  ('Fancy Lace', 'Lace', (SELECT id FROM product_categories WHERE lower(name) = lower('Lace')), 'LACE', 'Soft and delicate decorative lace available in multiple designs.', 'Polyester / Synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Delicate']::text[], NULL, 'PKR', true, '[["Product type","Fancy lace"],["Material composition","Polyester / synthetic fiber"],["Available widths","Various"],["Color options","Multiple colors"],["Design options","Various designs"],["Finish","Soft / delicate"],["Applications","Garments, lingerie, crafts, home decor"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Fancy_Lace.webp","fileId":"6aae15c7ead997d09ae7d213","name":"Fancy_Lace.webp","width":null,"height":null}]'::jsonb),
  ('All Fancy Cords', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'CORD', 'Decorative and durable cords available in multiple textile materials and designs.', 'Nylon / Polyester / Polypropylene / Acrylic / Cotton', NULL, ARRAY['Multiple colors']::text[], ARRAY['Decorative']::text[], NULL, 'PKR', true, '[["Product type","Fancy cord"],["Material composition","Nylon / Polyester / Polypropylene / Acrylic / Cotton"],["Available widths","Various"],["Color options","Multiple colors"],["Design options","Various designs"],["Finish","Decorative"],["Applications","Garments, bags, accessories, crafts"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Fancy_Cords.webp","fileId":"6aae15caead997d09ae7dd55","name":"Fancy_Cords.webp","width":null,"height":null}]'::jsonb),
  ('Jute Cord', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'CORD', 'Natural, strong and biodegradable jute cord.', 'Jute', NULL, ARRAY['Natural', 'Multiple colors']::text[], ARRAY['Natural']::text[], NULL, 'PKR', true, '[["Product type","Jute cord"],["Material composition","Jute"],["Available widths","Various"],["Color options","Natural and multiple colors"],["Finish","Natural"],["Applications","Crafts, packaging, home decor"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Jute_Cord.webp","fileId":"6aae15ccead997d09ae7e349","name":"Jute_Cord.webp","width":null,"height":null}]'::jsonb),
  ('Braid Rope', 'Egg Belts', (SELECT id FROM product_categories WHERE lower(name) = lower('Egg Belts')), 'EGG BELT', 'Durable braided rope manufactured from Nylon, Polyester, and Polypropylene, available in 5mm–20mm thicknesses and customized lengths according to customer requirements.', 'Nylon, Polyester & Polypropylene', 5, ARRAY['White']::text[], ARRAY['Braided rope']::text[], NULL, 'PKR', true, '[["Product type","Braid rope"],["Material","Nylon, Polyester & Polypropylene"],["Thickness","5mm to 20mm"],["Length","Depends on customer requirements"],["Color","White"],["Construction","Braided rope"],["Packing","Standard package"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Braid_Rope.webp","fileId":"6aae15d2ead997d09ae814e1","name":"Braid_Rope.webp","width":null,"height":null}]'::jsonb),
  ('Fancy Yarn', 'Yarn', (SELECT id FROM product_categories WHERE lower(name) = lower('Yarn')), 'YARN', 'Soft decorative yarn available in multiple colors and textures.', 'Acrylic / Cotton / Polyester', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Textured']::text[], NULL, 'PKR', true, '[["Product type","Fancy yarn"],["Material composition","Acrylic / Cotton / Polyester"],["Available sizes","Various"],["Color options","Multiple colors"],["Finish","Soft / textured"],["Applications","Knitting, crochet, crafts, embellishments"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/Fancy_Yarn.webp","fileId":"6aae15ceead997d09ae7f90e","name":"Fancy_Yarn.webp","width":null,"height":null}]'::jsonb),
  ('Pouch', 'Accessories', (SELECT id FROM product_categories WHERE lower(name) = lower('Accessories')), 'POUCH', 'Durable and soft pouches available in multiple sizes and colors.', 'Textile / Synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Durable']::text[], NULL, 'PKR', true, '[["Product type","Pouch"],["Material composition","Textile / synthetic fiber"],["Available sizes","Various"],["Color options","Multiple colors"],["Finish","Soft / durable"],["Applications","Storage, packaging, gifts"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/pouch.jpg","fileId":"6aacce4bead997d09a89ef66","name":"pouch.jpg","width":null,"height":null}]'::jsonb),
  ('PP Woven Egg Conveyor Belt', 'Egg Belts', (SELECT id FROM product_categories WHERE lower(name) = lower('Egg Belts')), 'EGG BELT', 'UV and anti-static treated PP woven belt for egg collection in poultry farms, with an egg broken rate below 0.3%.', 'Nylon / Polyester / Polypropylene', 90, '{}'::text[], ARRAY['UV & anti-static treated']::text[], NULL, 'PKR', true, '[["Product type","PP woven egg conveyor belt"],["Material composition","Nylon, polyester & polypropylene"],["Available widths","90–120mm"],["Length","Custom"],["Egg broken rate","Below 0.3%"],["Applications","Poultry farm egg collecting, assembly-line conveyor belts"],["Finish","UV & anti-static treated, washable in cold water"]]'::jsonb, '[{"url":"https://ik.imagekit.io/a2q8u8qtw/products/pp_woven_egg_conveyor_belt.avif","fileId":"6aae1627ead997d09ae97070","name":"pp_woven_egg_conveyor_belt.avif","width":null,"height":null}]'::jsonb)
ON CONFLICT (name) DO NOTHING;
