-- ============================================================================
-- SEED — PRODUCT CATALOG from the live showroom
-- ----------------------------------------------------------------------------
-- GENERATED FILE — do not edit by hand.
--   pnpm exec node scripts/generate-catalog-seed.mjs
--
-- Source of truth: components/showroom-section.tsx (names, descriptions,
-- materials, specs, CDN images) and lib/showroom.ts (category names).
--
-- Run AFTER supabase/migrations/0002_products_catalog.sql.
--
--   * 'on conflict (name) do nothing' => re-running is safe and never
--     overwrites a product an admin has edited, renamed or deactivated.
--   * price_per_unit is left NULL on purpose: the showroom publishes no prices
--     because quotes are negotiated. Set prices in /admin/products.
--   * moq_units is NULL for the 38 products whose showroom entry publishes no
--     "Minimum order quantity" spec — the site never stated one, so the seed
--     does not invent one. Fill them in at /admin/products.
--   * images[].fileId is NULL: these files were uploaded to ImageKit outside
--     this app, so the admin UI will never delete them from the CDN.
--   * width_mm stores the nominal lower bound of the published range.
-- ============================================================================

INSERT INTO products (
  name, category, category_id, description, material, width_mm,
  available_colors, available_finishes, moq_units, currency, is_active, images
) VALUES
  ('Fringe Lace', 'Lace', (SELECT id FROM product_categories WHERE lower(name) = lower('Lace')), 'Soft, expressive fringe for trims and statement edges.', 'Cotton blend', 10, '{}'::text[], ARRAY['Natural']::text[], 500, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/all%20Cotton%20Fringe.webp","fileId":null,"name":"all Cotton Fringe.webp","width":null,"height":null}]'::jsonb),
  ('Golden Tassel', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'A polished accent with a warm metallic finish for elevated details.', 'Polyester', 30, ARRAY['Gold tones']::text[], ARRAY['Metallic']::text[], 250, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Golden%20Tassel.webp","fileId":null,"name":"Golden Tassel.webp","width":null,"height":null}]'::jsonb),
  ('Metal Cord', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'Structured cord with a refined surface texture.', 'Metallic yarn', 2, '{}'::text[], ARRAY['Polished']::text[], 500, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Metal%20Cord.webp","fileId":null,"name":"Metal Cord.webp","width":null,"height":null}]'::jsonb),
  ('Pom Pom Trim', 'Pom Poms', (SELECT id FROM product_categories WHERE lower(name) = lower('Pom Poms')), 'Playful volume for apparel and home details.', 'Polyester', 10, '{}'::text[], ARRAY['Soft']::text[], 500, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Pom%20Pom%20Trim.webp","fileId":null,"name":"Pom Pom Trim.webp","width":null,"height":null}]'::jsonb),
  ('Cotton Fringe', 'Lace', (SELECT id FROM product_categories WHERE lower(name) = lower('Lace')), 'Natural cotton texture with an easy, soft hand.', '100% cotton', 25, '{}'::text[], ARRAY['Natural']::text[], 500, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Cotton%20Fringe.webp","fileId":null,"name":"Cotton Fringe.webp","width":null,"height":null}]'::jsonb),
  ('Woven Belt', 'Belts', (SELECT id FROM product_categories WHERE lower(name) = lower('Belts')), 'Hard-wearing woven utility trim made for scale.', 'Polyester', 25, '{}'::text[], ARRAY['Durable']::text[], 500, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Woven%20Belt.webp","fileId":null,"name":"Woven Belt.webp","width":null,"height":null}]'::jsonb),
  ('Needle Loom Elastic', 'Elastics', (SELECT id FROM product_categories WHERE lower(name) = lower('Elastics')), 'Strong, durable elastic with a soft and smooth finish.', 'Nylon / Polyester', NULL, ARRAY['White', 'Black', 'Natural', 'Beige', 'Grey', 'Navy Blue', 'Brown', 'Multi Color']::text[], ARRAY['Soft / Smooth']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Needle%20Loom%20Elastic.webp","fileId":null,"name":"Needle Loom Elastic.webp","width":null,"height":null}]'::jsonb),
  ('Crochet Elastic', 'Elastics', (SELECT id FROM product_categories WHERE lower(name) = lower('Elastics')), 'Stretchy, durable crochet elastic designed for comfortable textile applications.', 'Latex / Polyester', NULL, ARRAY['White', 'Black', 'Beige', 'Grey', 'Navy Blue', 'Multi Color']::text[], ARRAY['Soft / Flexible']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Crochet%20Elastic.webp","fileId":null,"name":"Crochet Elastic.webp","width":null,"height":null}]'::jsonb),
  ('Jacquard Elastic & Tape', 'Elastics', (SELECT id FROM product_categories WHERE lower(name) = lower('Elastics')), 'Strong jacquard elastic and tape with custom branding and woven designs.', 'Nylon / Polyester', NULL, '{}'::text[], ARRAY['Woven / Jacquard']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Jacquard%20Elastic%20&%20Tape.webp","fileId":null,"name":"Jacquard Elastic & Tape.webp","width":null,"height":null}]'::jsonb),
  ('Elastics', 'Elastics', (SELECT id FROM product_categories WHERE lower(name) = lower('Elastics')), 'General-purpose textile elastics available in multiple materials and colors.', 'Nylon / Polyester / Polypropylene', NULL, ARRAY['Multiple colors']::text[], ARRAY['Flexible']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Elastics.webp","fileId":null,"name":"Elastics.webp","width":null,"height":null}]'::jsonb),
  ('Draw Cord', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'Strong and flexible draw cord available in solid, striped and patterned designs.', 'Nylon / Polyester / Polypropylene / Cotton', NULL, ARRAY['Custom', 'Multiple colors']::text[], ARRAY['Various finishes']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Draw%20Cord.webp","fileId":null,"name":"Draw Cord.webp","width":null,"height":null}]'::jsonb),
  ('Flat Draw Cord', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'Strong, smooth flat draw cord for garment and sportswear applications.', 'Polyester / Nylon', NULL, ARRAY['Blue', 'White', 'Black', 'White', 'Green', 'White', 'Red', 'White', 'Purple', 'White', 'Multi Color']::text[], ARRAY['Soft / Smooth']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Flat%20Draw%20Cord.webp","fileId":null,"name":"Flat Draw Cord.webp","width":null,"height":null}]'::jsonb),
  ('Drawstring Cord', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'Durable, flexible drawstring cord available in a range of finishes.', 'Polyester / Nylon', NULL, ARRAY['Custom', 'Multiple colors']::text[], ARRAY['Various finishes']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Drawstring%20Cord.webp","fileId":null,"name":"Drawstring Cord.webp","width":null,"height":null}]'::jsonb),
  ('Cord with Tassel', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'Decorative cord finished with an elegant tassel end.', 'Polyester / Synthetic fiber', NULL, ARRAY['Gold', 'Gold', 'Metallic']::text[], ARRAY['Metallic']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Cord%20with%20Tassel.webp","fileId":null,"name":"Cord with Tassel.webp","width":null,"height":null}]'::jsonb),
  ('Draw Cord Tassel', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'Colorful decorative tassel finish for drawstrings and accessories.', 'Synthetic fiber', NULL, ARRAY['Multi Color']::text[], ARRAY['Tassel']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Draw%20Cord%20with%20Tassel.webp","fileId":null,"name":"Draw Cord with Tassel.webp","width":null,"height":null}]'::jsonb),
  ('Multi Color Tassel', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'Soft, colorful fringed tassels available in different lengths.', 'Synthetic fiber', NULL, ARRAY['Multi Color']::text[], ARRAY['Fringed']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Multi%20Color%20Tassel.webp","fileId":null,"name":"Multi Color Tassel.webp","width":null,"height":null}]'::jsonb),
  ('Tassels', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'Classic decorative tassels for garments, bags, and home d�cor.', 'Polyester / Synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Decorative']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Tassel.webp","fileId":null,"name":"Tassel.webp","width":null,"height":null}]'::jsonb),
  ('Flat Shoelaces', 'Shoelaces', (SELECT id FROM product_categories WHERE lower(name) = lower('Shoelaces')), 'Durable flat shoelaces available in multiple colors and patterns.', 'Polyester / Nylon', NULL, ARRAY['White', 'Black', 'Grey', 'Navy Blue', 'Red', 'Royal Blue', 'Beige', 'Brown', 'Neon Green', 'Purple Metallic', 'White', 'Cream', 'Black', 'White Striped', 'Orange', 'Tan Metallic', 'Cream', 'Beige', 'Yellow', 'Green', 'Patterned', 'Multi Color']::text[], ARRAY['Woven / Soft']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Flat%20Shoelaces.webp","fileId":null,"name":"Flat Shoelaces.webp","width":null,"height":null}]'::jsonb),
  ('Waxy Shoelaces', 'Shoelaces', (SELECT id FROM product_categories WHERE lower(name) = lower('Shoelaces')), 'High-strength wax-coated shoelaces designed for durability and a tangle-free finish.', 'Polyester / Nylon', NULL, ARRAY['Black', 'Brown', 'Dark Brown', 'Navy Blue', 'Grey', 'White', 'Beige', 'Multi Color']::text[], ARRAY['Wax Coated']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Waxy%20Shoelaces.webp","fileId":null,"name":"Waxy Shoelaces.webp","width":null,"height":null}]'::jsonb),
  ('Tricot Knitting Tape', 'Tapes', (SELECT id FROM product_categories WHERE lower(name) = lower('Tapes')), 'Strong and smooth knitted tape for garment construction and finishing.', 'Polyester / Nylon', NULL, ARRAY['White', 'White', 'Navy', 'White', 'Black', 'Red', 'White', 'Black', 'Red', 'Green', 'Multi', 'Silver Stripe']::text[], ARRAY['Soft / Smooth']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Tricot%20Knitting%20Tape.webp","fileId":null,"name":"Tricot Knitting Tape.webp","width":null,"height":null}]'::jsonb),
  ('Twill Tape', 'Tapes', (SELECT id FROM product_categories WHERE lower(name) = lower('Tapes')), 'Strong and flexible twill tape available in multiple widths and colors.', 'Cotton / Polyester', 10, ARRAY['Multiple colors']::text[], ARRAY['Twill Weave']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Twill%20Tape.webp","fileId":null,"name":"Twill Tape.webp","width":null,"height":null}]'::jsonb),
  ('Neck Tapes', 'Tapes', (SELECT id FROM product_categories WHERE lower(name) = lower('Tapes')), 'Soft woven neck tape designed for comfortable garment finishing.', 'Polyester / Nylon', NULL, ARRAY['Red', 'Green', 'Light Blue', 'Black', 'White', 'Beige', 'Royal Blue', 'Mint', 'Purple', 'Multipack']::text[], ARRAY['Soft / Woven']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Neck%20Tapes.webp","fileId":null,"name":"Neck Tapes.webp","width":null,"height":null}]'::jsonb),
  ('Mesh Ribbon', 'Ribbons', (SELECT id FROM product_categories WHERE lower(name) = lower('Ribbons')), 'Soft, breathable decorative mesh ribbon for textile and craft applications.', 'Polyester', NULL, ARRAY['White']::text[], ARRAY['Soft / Breathable']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Mesh%20Ribbon.webp","fileId":null,"name":"Mesh Ribbon.webp","width":null,"height":null}]'::jsonb),
  ('Ribbons', 'Ribbons', (SELECT id FROM product_categories WHERE lower(name) = lower('Ribbons')), 'Decorative ribbons available in multiple colors and widths.', 'Polyester / Synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Decorative']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Ribbons.webp","fileId":null,"name":"Ribbons.webp","width":null,"height":null}]'::jsonb),
  ('Web Tape', 'Tapes', (SELECT id FROM product_categories WHERE lower(name) = lower('Tapes')), 'Clean woven construction for dependable finishing and repeat production.', 'Polyester / Polypropylene', NULL, ARRAY['Various']::text[], ARRAY['Woven']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Web%20Tape.webp","fileId":null,"name":"Web Tape.webp","width":null,"height":null}]'::jsonb),
  ('Jute Tape', 'Tapes', (SELECT id FROM product_categories WHERE lower(name) = lower('Tapes')), 'Natural, strong and biodegradable jute tape.', 'Jute', NULL, ARRAY['Natural', 'Multiple colors']::text[], ARRAY['Natural']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Jute%20Tape.webp","fileId":null,"name":"Jute Tape.webp","width":null,"height":null}]'::jsonb),
  ('Label Tape', 'Tapes', (SELECT id FROM product_categories WHERE lower(name) = lower('Tapes')), 'Printable label tape for branding and garment identification.', 'Polyester', NULL, ARRAY['Multiple colors']::text[], ARRAY['Printable']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Label%20Tape.webp","fileId":null,"name":"Label Tape.webp","width":null,"height":null}]'::jsonb),
  ('Waist Belt', 'Belts', (SELECT id FROM product_categories WHERE lower(name) = lower('Belts')), 'Recycled material belt for sustainable garment production.', 'Recycled material', NULL, ARRAY['Various']::text[], ARRAY['Utility']::text[], NULL, 'PKR', true, '[{"url":"/product%20images%20compressed/Waste%20Belt_compressed.webp","fileId":null,"name":"Waste Belt_compressed.webp","width":null,"height":null}]'::jsonb),
  ('Cotton Belts', 'Belts', (SELECT id FROM product_categories WHERE lower(name) = lower('Belts')), 'Natural cotton belt available in multiple widths and colors.', '100% Cotton', NULL, ARRAY['Multiple colors']::text[], ARRAY['Natural / Soft']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Cotton%20Belts.webp","fileId":null,"name":"Cotton Belts.webp","width":null,"height":null}]'::jsonb),
  ('All Types Belts', 'Belts', (SELECT id FROM product_categories WHERE lower(name) = lower('Belts')), 'Multi-material belts including nylon, polyester, polypropylene, and cotton.', 'Nylon / Polyester / Polypropylene / Cotton', NULL, ARRAY['Multiple colors']::text[], ARRAY['Woven']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/all%20Cotton%20Belts.webp","fileId":null,"name":"all Cotton Belts.webp","width":null,"height":null}]'::jsonb),
  ('Pom-pom', 'Pom Poms', (SELECT id FROM product_categories WHERE lower(name) = lower('Pom Poms')), 'Soft, playful pom-poms available in multiple colors and sizes.', 'Acrylic / synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Plush']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Pom%20Pom.webp","fileId":null,"name":"Pom Pom.webp","width":null,"height":null}]'::jsonb),
  ('Pom Pom Lace', 'Pom Poms', (SELECT id FROM product_categories WHERE lower(name) = lower('Pom Poms')), 'Decorative pom-pom lace trim for garments and accessories.', 'Acrylic / synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Plush']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Pom%20Pom%20lace.webp","fileId":null,"name":"Pom Pom lace.webp","width":null,"height":null}]'::jsonb),
  ('Pom Pom Ball', 'Pom Poms', (SELECT id FROM product_categories WHERE lower(name) = lower('Pom Poms')), 'Round pom-pom balls available in multiple sizes and colors.', 'Acrylic / synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Plush']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Pom%20Pom%20Ball.webp","fileId":null,"name":"Pom Pom Ball.webp","width":null,"height":null}]'::jsonb),
  ('Pom Pom Toys', 'Pom Poms', (SELECT id FROM product_categories WHERE lower(name) = lower('Pom Poms')), 'Soft, playful pom-pom toys for children and crafts.', 'Acrylic / synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Playful']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Pom%20Pom%20toys.webp","fileId":null,"name":"Pom Pom toys.webp","width":null,"height":null}]'::jsonb),
  ('Pom Pom Flower', 'Pom Poms', (SELECT id FROM product_categories WHERE lower(name) = lower('Pom Poms')), 'Decorative pom-pom flowers for garments and home d�cor.', 'Acrylic / synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Decorative']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Pom%20Pom%20Flower.webp","fileId":null,"name":"Pom Pom Flower.webp","width":null,"height":null}]'::jsonb),
  ('Multi Pom Pom', 'Pom Poms', (SELECT id FROM product_categories WHERE lower(name) = lower('Pom Poms')), 'Multi-colored pom-poms available in various sizes.', 'Acrylic / synthetic fiber', NULL, ARRAY['Multi Color']::text[], ARRAY['Soft / Plush']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Multi%20Pom%20Pom.webp","fileId":null,"name":"Multi Pom Pom.webp","width":null,"height":null}]'::jsonb),
  ('Party Hat / Birthday Cap', 'Accessories', (SELECT id FROM product_categories WHERE lower(name) = lower('Accessories')), 'Decorative party hats and birthday caps available in multiple colors.', 'Paper / Cardboard / Synthetic', NULL, ARRAY['Multiple colors']::text[], ARRAY['Decorative']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Party%20Hat.webp","fileId":null,"name":"Party Hat.webp","width":null,"height":null}]'::jsonb),
  ('Fancy Lace', 'Lace', (SELECT id FROM product_categories WHERE lower(name) = lower('Lace')), 'Soft and delicate decorative lace available in multiple designs.', 'Polyester / Synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Delicate']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Fancy%20Lace.webp","fileId":null,"name":"Fancy Lace.webp","width":null,"height":null}]'::jsonb),
  ('All Fancy Cords', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'Decorative and durable cords available in multiple textile materials and designs.', 'Nylon / Polyester / Polypropylene / Acrylic / Cotton', NULL, ARRAY['Multiple colors']::text[], ARRAY['Decorative']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Fancy%20Cords.webp","fileId":null,"name":"Fancy Cords.webp","width":null,"height":null}]'::jsonb),
  ('Jute Cord', 'Cords & Tassels', (SELECT id FROM product_categories WHERE lower(name) = lower('Cords & Tassels')), 'Natural, strong and biodegradable jute cord.', 'Jute', NULL, ARRAY['Natural', 'Multiple colors']::text[], ARRAY['Natural']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Jute%20Cord.webp","fileId":null,"name":"Jute Cord.webp","width":null,"height":null}]'::jsonb),
  ('Braid Rope', 'Egg Belts', (SELECT id FROM product_categories WHERE lower(name) = lower('Egg Belts')), 'Durable braided rope manufactured from Nylon, Polyester, and Polypropylene, available in 5mm–20mm thicknesses and customized lengths according to customer requirements.', 'Nylon, Polyester & Polypropylene', 5, ARRAY['White']::text[], ARRAY['Braided rope']::text[], NULL, 'PKR', true, '[{"url":"/product%20images%20compressed/Braid%20Rope_compressed.webp","fileId":null,"name":"Braid Rope_compressed.webp","width":null,"height":null}]'::jsonb),
  ('Fancy Yarn', 'Yarn', (SELECT id FROM product_categories WHERE lower(name) = lower('Yarn')), 'Soft decorative yarn available in multiple colors and textures.', 'Acrylic / Cotton / Polyester', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Textured']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/Fancy%20Yarn.webp","fileId":null,"name":"Fancy Yarn.webp","width":null,"height":null}]'::jsonb),
  ('Pouch', 'Accessories', (SELECT id FROM product_categories WHERE lower(name) = lower('Accessories')), 'Durable and soft pouches available in multiple sizes and colors.', 'Textile / Synthetic fiber', NULL, ARRAY['Multiple colors']::text[], ARRAY['Soft / Durable']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/pouch.jpg","fileId":null,"name":"pouch.jpg","width":null,"height":null}]'::jsonb),
  ('PP Woven Egg Conveyor Belt', 'Egg Belts', (SELECT id FROM product_categories WHERE lower(name) = lower('Egg Belts')), 'UV and anti-static treated PP woven belt for egg collection in poultry farms, with an egg broken rate below 0.3%.', 'Nylon / Polyester / Polypropylene', 90, '{}'::text[], ARRAY['UV & anti-static treated']::text[], NULL, 'PKR', true, '[{"url":"https://ik.imagekit.io/wavawecyl/product%20images%20webp/PP%20Woven%20Egg%20Conveyor%20Belt.webp","fileId":null,"name":"PP Woven Egg Conveyor Belt.webp","width":null,"height":null}]'::jsonb)
ON CONFLICT (name) DO NOTHING;
