import Image from 'next/image'
import { SiteHeader } from './site-header'
import { SiteFooter } from './site-footer'

const factoryCards = [
  { title: '500k+ Meters / Month Capacity', image: 'https://ik.imagekit.io/wavawecyl/factory%20webp%20images/textile%20production.webp?updatedAt=1788845891400' },
  { title: 'Material Range', image: 'https://ik.imagekit.io/wavawecyl/factory%20webp%20images/Ethical%20Manufacturing.webp?updatedAt=1788845890872' },
  { title: 'Size & Width Tolerances', image: 'https://ik.imagekit.io/wavawecyl/factory%20webp%20images/Braiding%20&%20Winding.webp?updatedAt=1788845890777' },
  { title: 'Quality Inspection Protocol', image: 'https://ik.imagekit.io/wavawecyl/factory%20webp%20images/trims%20quality%20inspection.webp?updatedAt=1788845891491' },
  { title: 'Export Packaging', image: 'https://ik.imagekit.io/wavawecyl/factory%20webp%20images/global%20export.webp?updatedAt=1788845890936' },
  { title: 'Incoterms & Logistics', image: 'https://ik.imagekit.io/wavawecyl/factory%20webp%20images/Logistics%20&%20Export.webp?updatedAt=1788845890992' },
]

function DarkShell({ children }: { children: React.ReactNode }) {
  return <main className="relative min-h-screen bg-[#0a0c0b] text-white"><div aria-hidden="true" className="absolute inset-x-0 top-0 z-0 h-[min(760px,100vh)] overflow-hidden lg:h-[100vh]"><Image src="/images/trims2.webp" alt="" priority fetchPriority="high" fill sizes="100vw" quality={70} className="size-full object-cover" /><div className="absolute inset-0 bg-black/40" /><div className="absolute inset-0 bg-gradient-to-b from-black/55 via-black/30 to-[#0a0c0b]" /></div><div className="relative z-10"><SiteHeader />{children}<SiteFooter /></div></main>
}

export function FactoryPage() {
  return <DarkShell><section className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#00c853]">Our operation</p><h1 className="mt-2 max-w-2xl font-[family-name:var(--font-fraunces)] text-3xl font-semibold tracking-tight sm:text-5xl">Faisalabad Manufacturing Base & Capacity</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/60">Reliable production for global trims programs, from sampling through repeat manufacturing.</p><div className="mt-8 grid gap-3 md:grid-cols-3">{['https://ik.imagekit.io/wavawecyl/factory%20webp%20images/textile%20production.webp?updatedAt=1788845891400','https://ik.imagekit.io/wavawecyl/factory%20webp%20images/Braiding%20&%20Winding.webp?updatedAt=1788845890777','https://ik.imagekit.io/wavawecyl/factory%20webp%20images/packed%20inventory.webp?updatedAt=1788845891361'].map((src,i)=><div key={i} className="relative aspect-[1.55] overflow-hidden rounded-xl border border-white/10"><Image src={src} alt="Textile manufacturing detail" fill quality={55} sizes="(min-width: 768px) 33vw, calc(100vw - 40px)" className="size-full object-cover" /><span className="absolute bottom-3 left-3 text-xs font-medium text-white">{['Material preparation','Production floor','Packed inventory'][i]}</span></div>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{factoryCards.filter(c=>!['500k+ Meters / Month Capacity','Material Range','Size & Width Tolerances'].includes(c.title)).map((x)=><article key={x.title} className="relative overflow-hidden rounded-2xl border border-white/10 bg-[#101413]"><div className="relative aspect-[16/10] overflow-hidden bg-black/40"><Image src={x.image} alt={x.title} fill loading="lazy" quality={55} sizes="(min-width: 1024px) 25vw, (min-width: 640px) 50vw, calc(100vw - 40px)" className="size-full object-cover" /></div><div className="p-4"><h2 className="text-sm font-semibold text-white">{x.title}</h2><p className="mt-2 text-xs leading-5 text-white/55">Consistent processes, clear specifications, and dependable communication for every order.</p></div></article>)}</div></section></DarkShell>
}